development: 
  :host: localhost
  :port: 6379
  :password:
  :database: 15
test: 
  :host: localhost
  :port: 6379
  :password: 
  :database: 15
production:
  :host: localhost
  :port: 6379
  :password:
  :database: 1